my_string = input('Введите любой текст из нескольких слов: ')
print('Общее количество символов в тексте (включая пробелы):',len(my_string))
print('Текст в верхнем регистре: ' + my_string.upper())
print('Текст в нижнем регистре: ' + my_string.lower())
print('Текст без пробелов: ' + my_string.replace(' ', ''))
print('Первый символ строки: ' + my_string[0])
print('Последний символ строки: ' + my_string[-1])